### ISSUE TITLE
参数在哪个位置填写？

### ISSUE THREAD

**Issue by Hansen1018** [neoblackxt/PTMyBonusCalc#6]
不太清楚在编辑器源码哪个位置填写或者替换

**Comment by neoblackxt** [comment]
1. 打开扩展选项
![Screenshot 2024-12-17 235844](https://github.com/user-attachments/assets/40c4daa9-b450-444f-8816-b450427cd3e3)
2. 把配置模式设置为高级模式
![Screenshot 2024-12-17 235102](https://github.com/user-attachments/assets/5e609c34-37a6-4cb7-8323-435076c9b84e)
3. 在已安装脚本中找到“魔力值计算器”，点击编辑按钮
![Screenshot 2024-12-18 000242](https://github.com/user-attachments/assets/d28a8371-5b1e-4ef6-9e42-e2f668189463)
4. 在存储中修改参数数据
![Screenshot 2024-12-18 000418](https://github.com/user-attachments/assets/ca9b63cb-23b2-482f-a792-fc2791d74731)

**Comment by Hansen1018** [comment]
其实打开馒头魔力值页面自动更新，不过插件时不时失效，前几次都是读取失败来问。刚才在你回复之前打开页面突然自动读取到了

现在打开种子板块也是时不时失效（不显示）

**Comment by neoblackxt** [comment]
参数的格式：
```
{
    "域名.B0": 参数值,
    "域名.L": 参数值,
    "域名.N0": 参数值,
    "域名.T0":参数值
}
```
例如：
```
{
    "soulvoice.club.B0": 100,
    "soulvoice.club.L": 300,
    "soulvoice.club.N0": 10,
    "soulvoice.club.T0": 4
}
```

**Comment by neoblackxt** [comment]
脚本失效时可以刷新一下页面，失效原因尚不清楚。可能与网页的部分刷新方式和脚本的加载时机有关。

**Comment by Hansen1018** [comment]
谢谢

**Comment by gxcnlee** [comment]
设置高级了，也重启插件了，可是编辑脚本死活没有，资源这个选项，这可怎么办
